### ISSUE TITLE
trade feeds / CVD not working

### ISSUE THREAD

**Issue by elijhhhh** [Tucsky/aggr#150] opened 2022-01-02 02:33 UTC
Is there something wrong with trade feeds and CVDs not working after a few minutes for some exchanges? Cause the feed just completely stops after a few minutes and I’ll refresh it and it just repeats. Same as CVDs for those exchanges it stops also after a few minutes? (coinbase, finex, nance, mex etc..)

**Comment by elijhhhh** [comment] 2022-01-02 02:38
https://media.discordapp.net/attachments/842555605298315296/926659873951875112/unknown.png

**Comment by elijhhhh** [comment] 2022-01-02 02:40
![image](https://user-images.githubusercontent.com/96964452/147864606-4f38baa5-36e3-4043-941e-0201f4c2efe8.png)

**Comment by elijhhhh** [comment] 2022-01-02 02:43
41 minutes and there hasn't been anything on the feed and when i refresh it starts showing trades and stops again after a minute or so and cvd stops also

**Comment by Tucsky** [comment] 2022-01-02 11:01
Never had this but ty for reporting 👍🏼! Please send me your workspace see if there is something weird with it
( Settings > workspace (blue button) > download )

Is the app all unresponsive / freezing when this happen or is it just the data stop updating? 

Anything weird in the console tab of chrome ? (F12>console)

**Comment by elijhhhh** [comment] 2022-01-02 21:56
![image](https://user-images.githubusercontent.com/96964452/147890466-1953c02b-c303-4cf8-80c5-95e26ad6c6ac.png)

**Comment by elijhhhh** [comment] 2022-01-02 21:57
Could this be the problem? Sorry I know nothing about coding

**Comment by Tucsky** [comment] 2022-01-03 15:05
> Could this be the problem? Sorry I know nothing about coding

looks like a network issue on your end

**Comment by elijhhhh** [comment] 2022-01-03 19:41
is there any way to fix it?

**Comment by gimple** [comment] 2022-01-07 07:32
this is definitely a networking issue on your end of things.  would be able to help you troubleshoot this, what browser are you using?  that's chrome's inspector/dev tools, but it also looks this way in brave as well.  perhaps you have settings for blocking certain third party resources in brave, i'm not sure.  that's what comes to mind with the googletagmanager url error, anyway.  

have you tried to see what happens in another browser?  open the developer tools console back up, and open the tab that says 'network' along the top when you have the site tab open in the browser.  once it's loaded up, hit F5/refresh the tab and check as the different connections start to happen.  you can filter it by errors/warnings you get when it's done, look thru that for a better idea of where the problems are happening.

**Comment by MatJohnson** [comment] 2022-01-09 11:02
I too am also having the same issue since approximately 7 days ago - it would be unusual for both of us to suddenly start having network issues at the same time. 

![image](https://user-images.githubusercontent.com/24913075/148679451-464eb5c8-d0a9-425a-ac56-bdd1de96c20b.png)

**Comment by Tucsky** [comment] 2022-01-09 14:47
I'm willing to fix this but I just can't reproduce the issue rn
I need more info, anything can help (**full logs** when running the app locally, workspace file, what browser are you using ect)
Also please make sure you are running the latest version (3.0.7 - 31dec)

@MatJohnson
If I understand correctly you are able to running it locally, it will help a lot if you can share the logs! (when running it dev mode the logs are showing)
![image](https://user-images.githubusercontent.com/5738336/148687320-79083917-f931-49fe-aecc-3ef276082951.png)


> Also comparing the public aggr to the feed from my local aggr-server i am not receiving some trade information from public aggr

What difference did you noticed ?

**Comment by Tucsky** [comment] 2022-01-20 16:22
I think this might have been fixed in the 3.0.8  🤔 
not sure since I never had the issue 

Feel free to reopen if feeds / chart starts freezing again

**Closed by Tucsky** 2022-01-20 16:22 UTC
