### ISSUE TITLE
V3 new pair setup is inefficient

### ISSUE THREAD

**Issue by abn2609** [Tucsky/aggr#26] opened 2021-06-18 05:50 UTC
Hey team,

V3 looks new and all but it does take time to set up a different coin for example ETH.

V2 required a simple input into the "Pair" field and it would populate it for all exchanges available, a 5 second job at most.
V3 seems to require you to click every exchange to remove the current pair btc for like 18 exchanges, then you have to search the coin you want and then click every exchange you want for that coin.

It's a bit too different and complex to V2 that it so far feels more like a downgrade than an upgrade, if you could delay V2's phasing out as long as possible (or until setting up becomes as simple as V2), that would be much appreciated.

Thanks again and keep it up the good work.

**Comment by Tucsky** [comment] 2021-06-18 12:29
> if you could delay V2's phasing out as long as possible
v2 will remain on v2.aggr.trade for a while after aggr.trade get the update

About the search feature let's continue the discussion [here](https://github.com/Tucsky/aggr/issues/9)

Duplicate of #9

**Closed by Tucsky** 2021-06-18 12:29 UTC
