### ISSUE TITLE
Forex 24h Market Clock not displaying properly

### ISSUE THREAD

**Issue by VanessaE** [Tucsky/aggr#327] opened 2023-06-07 00:57 UTC
- [X] I added my [browser's console]
    
[errors.txt](https://github.com/Tucsky/aggr/files/11671344/errors.txt)

- [X] I have attached [an export of my aggr database](https://imgur.com/a/traIrKb) in the issue
    
[standard-layout.txt](https://github.com/Tucsky/aggr/files/11671346/standard-layout.txt)

- [X] I documented the issue with screenshots

![image](https://github.com/Tucsky/aggr/assets/1733537/e7bfec8f-72cf-435e-afde-784556f977ea)
![image](https://github.com/Tucsky/aggr/assets/1733537/8d4db8c9-f4b4-4386-8c70-c17b2576b8a3)

- [X] I provided a clear and concise description of what the bug is (see both sections below)

### Describe the issue

The Forex 24h Market Clock website, which had worked reliably for quite some time, no longer displays properly when docked into my aggr layout.   Instead, all I see is a mostly-empty clock face.

They began having a problem on their end recently, something related to their service provider refusing to serve the page, but that's since ended.  

If I use the reload function in the pane's header bar menu, or if I simply reload the whole Aggr page, the hands of the clock appear briefly, before being replaced by a mostly-empty clock face.

If I load the full site on a separate tab, it's fine.  The URL there is, https://market24hclock.com/

I disabled UBlock on both that site and on aggr.trade, but that didn't help.

Since it had worked before, I guess something important in their page code changed recently, breaking it for aggr.

### Steps to reproduce

Just load the attached layout/workspace and see what happens.

**Comment by adeacetis** [comment] 2023-06-07 09:03
Hello Vanessa,

Thank you for filling out such an exhaustive ticket. Not everyone takes the time to do so.

I hope I understood your problem. Have you tried to scroll inside the pane?

If you click on the small cog sitting on the top right of this page, you can enable Interactive options which will allow you to scroll the website inside the pane and then center the clock like so:
![image](https://github.com/Tucsky/aggr/assets/20586054/715bdad8-a984-48b1-9265-70803f88ece8)

Then just scroll inside the pane to center the clock and disable the Interactive option so the clock could fill the whole space. I have noticed that the scrolling settings would reset if I reload the page making, de facto, the clock uncentered.

Is that helping you?

![image](https://github.com/Tucsky/aggr/assets/20586054/5435cec6-514c-430e-b4c7-43f395eb9b71)

**Comment by adeacetis** [comment] 2023-06-07 10:19
Hello Vanessa,

I tested on: 
- aggr.trade
- charts.aggr.trade

I did all your steps and the clock keeps reappearing in its full shape and working properly.

This is how it looks after I reload from the pane's settings menu.
![image](https://github.com/Tucsky/aggr/assets/20586054/3a9514aa-2f4f-4799-974c-161da40e414d)

When I reload the whole page:
![image](https://github.com/Tucsky/aggr/assets/20586054/45622ea1-e7df-4ef6-8026-c50ab3c9c265)

Although, the URL parameters aren't working as explained in #210.

Did you try to disable all your browser plugins?

**Comment by VanessaE** [comment] 2023-06-07 18:29
* Disabling all extensions didn't help.
* Clearing browser history/data for aggr and the clock website didn't help.
* Deleting aggr workspaces didn't help.
* The size of the browser window has no effect.
* Removing all other panes in the layout, leaving just the clock website has no effect.
* I even tried creating a completely new layout, i.e. the aggr.trade default, and adding the website pane.  That didn't help.
* My system had a number of updates pending that I'd been putting off for several days as they'd require a reboot.  A new browser version was among them.  Applying those updates and rebooting did not help.  (Google Chrome, btw, which is now at v114.0.5735.106).  My uptime! :cry: 

And responding to remarks that I saw in email but which aren't on this page anymore:

* Scrolling the pane has no effect.  As you said, reloading the page or pane resets the scroll position, which makes it impossible to capture a centered image of the clock when the hands are momentarily visible.  (otherwise I would have centered the clock in both images).
* The pane is already set to interactive mode.

FINALLY:

The only thing that DID work was clearing all cookies and "other site data" (whatever that amounts to) and cached images/files, for the entire history thereof.

Obviously I can't just go around clearing my history all the time, since that also logs me out of websites and trashes things that depend on cookies like some websites' layouts or user settings.  Maybe there was some invalid/broken javascript in a cached file?

**Comment by adeacetis** [comment] 2023-06-08 09:48
Hopefully, the solution offered in #210 will help as well.

**Comment by adeacetis** [comment] 2023-06-08 21:14
Closing this as you found a solution to your problem. Don't hesitate to reopen it, however, the problem is most likely not coming from us.

**Closed by adeacetis** 2023-06-08 21:14 UTC
Labels: bug, can't repro
