### ISSUE TITLE
Please keep V2 so that it can switch back and forth

### ISSUE THREAD

**Issue by niceQVQ** [Tucsky/aggr#6] opened 2021-06-13 05:46 UTC
First of all, thank you very much. I like this project very much. It's very important for my transaction.I hope the order columns of V3 can be merged together instead of three independent columns. I hope there can be the function of merging and splitting or keep the V2 layout, let users switch back and forth according to their preferences.

**Comment by Tucsky** [comment] 2021-06-13 10:37
Duplicate of #4

**Closed by Tucsky** 2021-06-13 10:37 UTC
